name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v4

    - name: Instalar .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar solução
      run: dotnet build PokemonApiSolution.sln --no-restore --configuration Release

    - name: Executar testes
      run: dotnet test PokemonApiSolution.sln --no-build --configuration Release
